### ISSUE TITLE
Awair Glow not discovered

### ISSUE THREAD

**Issue by netmanchris** [danielsjf/awair_component#3]
@danielsjf 

Hoping you can help me troubleshoot this. 

- platform: awair
    token: !secret awair_token
    name: Bedroom Glow
    monitored_conditions:
      - temperature
      - humidity
      - co2
      - chemicals
    refresh_rate: 15

I removed the "dust" from the monitored conditions as dust is not an available sensor on the Awair Glow.
None of the Awair Glow's sensors are showing up. 

This same configuration does work fine with the Awair Gen1 and Gen2 so I know the integration is working. Educated guess, but is it possible that the lack of the Awair Glow is causing the addition of this platform to fail?   

Limited experience troubleshooting Hass so any pointers here would be greatly appreciated.

**Comment by netmanchris** [comment]
@danielsjf 

Looks like this might be the culprit 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/awair.py", line 60, in setup_platform
    awair_poller = AwairDev(name, awair_auth, refresh_rate)
  File "/config/deps/lib/python3.6/site-packages/pyawair/objects.py", line 45, in __init__
    self.refresh()
  File "/config/deps/lib/python3.6/site-packages/pyawair/objects.py", line 106, in refresh
    self._data['dust'] = data[-1]['sensors'][4]['value']
IndexError: list index out of range

Fixed in: https://github.com/netmanchris/pyawair/commit/3a08f84bfafdf01b89d09380e5d4a587646657df

Closing this as issue is resolved in pyawair library v 0.0.11
